/**
 * Import visual tokens — Figma page `62939:4277`, Main `62946:4425`.
 * Behavior stays in FEAT-007; this file is layout/chrome only.
 */

export const IMPORT = {
  padXPx: 16,
  padBottomPx: 16,
  panelGapPx: 10,
  titleSizePx: 20,
  titleLineHeightPx: 28,
  titleWeight: 600,
  titleColor: "#1d1b20",
  helperSizePx: 12,
  helperLineHeightPx: 18,
  helperColor: "#71717b",
  introGapPx: 4,
  pickerGapPx: 28,
  fieldGapPx: 8,
  textColor: "#1d1b20",
  filename: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  upload: {
    radiusPx: 8,
    padXPx: 18,
    padYPx: 16,
    gapPx: 16,
  },
  choose: {
    radiusPx: 8,
    padPx: 4,
    visualHeightPx: 28,
    hitHeightPx: 44,
    border: "#d1d1d6",
    fontSizePx: 12,
    lineHeightPx: 18,
  },
  start: {
    bg: "#f08429",
    color: "#ffffff",
    radiusPx: 8,
    padXPx: 4,
    padYPx: 8,
    visualHeightPx: 34,
    hitHeightPx: 44,
    fontSizePx: 14,
    lineHeightPx: 18,
    fontWeight: 600,
  },
  history: {
    radiusPx: 12,
    padXPx: 16,
    padTopPx: 10,
    padBottomPx: 18,
    gapPx: 8,
  },
  summary: {
    bg: "#f2f5ed",
    radiusPx: 8,
    padXPx: 18,
    padYPx: 16,
    gapPx: 16,
    titleSizePx: 18,
    titleLineHeightPx: 22,
    titleWeight: 500,
    titleColor: "#367057",
    countSizePx: 14,
    countLineHeightPx: 18,
    countWeight: 600,
    iconOuterWidthPx: 22,
    iconOuterHeightPx: 30,
    iconDrawWidthPx: 18,
    iconDrawHeightPx: 24,
    iconSrc: "/icons/file-waveform.svg",
  },
  batchList: {
    gapPx: 12,
    padTopPx: 8,
  },
  batch: {
    heightPx: 68,
    cardOffsetTopPx: 10,
    radiusPx: 8,
    border: "#d1d5dc",
    padLeftPx: 12,
    padRightPx: 16,
    padYPx: 10,
    gapPx: 4,
    metaWeight: 300,
    badgeRightPx: 10,
    badgeRadiusPx: 4,
    badgePadXPx: 5,
    badgePadYPx: 1,
    badgeCompleted: "#b7cc87",
    badgeProcessing: "#ffdb9c",
    badgeFailed: "#ff8c5a",
    badgeColor: "#000000",
    deleteColor: "#71717b",
    confirmDeleteColor: "#d95c1c",
  },
} as const;

export function getImportLayout() {
  return IMPORT;
}
